Default: &defaults
  database: haskell-kr.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: haskell-kr_test.sqlite3
  <<: *defaults

Staging:
  database: haskell-kr_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: haskell-kr_production.sqlite3
  poolsize: 100
  <<: *defaults
